name: Automated test suite

on:
  push:
    branches:
      - master
      - tests  # remove after merging into master
  pull_request:
    branches:
      - master
      - tests  # remove after merging into master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9.9', '3.10']
    steps:
      - name: Configure Git
        run: git config --global core.longpaths true
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install setuptools wheel build
      - name: Build and install
        run: |
          python -m build
          pip install --no-index --find-links dist/ dataintegrityfingerprint
      - name: Run tests
        run: |
          cd tests
          python -m unittest -v
